import math

PARAM_CW_MASS = 1250 # kg
PARAM_CABIN_EMPTY_MASS = 1000 # kg

PARAM_DT = 1e-6 # s

PARAM_RECTIFIER_V_BUS = 200.0 # V

PARAM_DC_MOTOR_RATED_RAD_S= 115 # rad/s
PARAM_DC_MOTOR_V_RATED = 200 # V
PARAM_DC_MOTOR_I_RATED = 75 # A
PARAM_DC_MOTOR_ARMATURE_RESISTANCE = 0.1 # Ohms
PARAM_DC_MOTOR_INDUCTANCE = 0.002 # H
PARAM_DC_MOTOR_K_T = 1.75 # Nm/A
PARAM_DC_MOTOR_K_B = 1.75 # V/(rad/s)
PARAM_DC_MOTOR_AND_GEARS_J = 0.2 # kg*m^2
PARAM_DC_MOTOR_VISCOUS_FRICTION = 0.0 # Nm/(rad/s)
PARAM_DC_MOTOR_RATED_TORQUE = PARAM_DC_MOTOR_I_RATED * PARAM_DC_MOTOR_K_T # Nm

# Calculate the current control gains
PARAM_DC_MOTOR_CURRENT_CONTROL_RISE_TIME = 0.010 # s
alfa_current_control = math.log(9)/PARAM_DC_MOTOR_CURRENT_CONTROL_RISE_TIME
PARAM_DC_MOTOR_CURRENT_CONTROL_Kp = alfa_current_control*PARAM_DC_MOTOR_INDUCTANCE
PARAM_DC_MOTOR_CURRENT_CONTROL_Ki = alfa_current_control*PARAM_DC_MOTOR_ARMATURE_RESISTANCE
PARAM_DC_MOTOR_CURRENT_CONTROL_OUTPUT_BOUNDS = (-PARAM_DC_MOTOR_V_RATED, PARAM_DC_MOTOR_V_RATED) # Voltage bound is the rated voltage

# Calculate the speed control gains
dc_motor_reflected_inertia = 1.0 # reflected inertia of the CW and Cabin
dc_motor_reflected_viscous_friction = PARAM_DC_MOTOR_VISCOUS_FRICTION #TODO: Add the damping of the load

PARAM_DC_MOTOR_SPEED_CONTROL_RISE_TIME = 5*PARAM_DC_MOTOR_CURRENT_CONTROL_RISE_TIME
alfa_speed_control = math.log(9)/PARAM_DC_MOTOR_SPEED_CONTROL_RISE_TIME
PARAM_DC_MOTOR_SPEED_CONTROL_Kp = alfa_speed_control*(dc_motor_reflected_inertia+PARAM_DC_MOTOR_AND_GEARS_J)/PARAM_DC_MOTOR_K_T
PARAM_DC_MOTOR_SPEED_CONTROL_Ki = alfa_speed_control*dc_motor_reflected_viscous_friction/PARAM_DC_MOTOR_K_T
PARAM_DC_MOTOR_SPEED_CONTROL_OUTPUT_BOUNDS = (-PARAM_DC_MOTOR_I_RATED, PARAM_DC_MOTOR_I_RATED) # Current bound is the rated current